### ISSUE TITLE
https://unstructured-io.github.io code example error.  (files > fileName)

### ISSUE THREAD

**Issue by pdkn** [Unstructured-IO/unstructured-js-client#24]
The Site docs need to be synced with this repos README.md

[https://unstructured-io.github.io/unstructured/apis/api_sdks.html](https://unstructured-io.github.io/unstructured/apis/api_sdks.html)

has
```
files: {
        content: data,
        files: filename,
    },
```

it should be 
[https://github.com/Unstructured-IO/unstructured-js-client/blob/main/README.md](https://github.com/Unstructured-IO/unstructured-js-client/blob/main/README.md)

```
files: {
        content: data,
        fileName: filename,
    },
```

(`files: filename,` renamed to ` fileName: filename,`)

**Comment by awalker4** [comment]
Thank you for flagging!

**Comment by ron-unstructured** [comment]
Fixed in this [PR](https://github.com/Unstructured-IO/unstructured/pull/2560)
