### ISSUE TITLE
Documentation: params need to be camelCase which differs from unstructured-api

### ISSUE THREAD

**Issue by kindziora** [Unstructured-IO/unstructured-js-client#30]
Thanks for providing the TS-client.

unstructured-api partition arguments need to be snake_case.
_https://github.com/Unstructured-IO/unstructured-api_

unstructured-js-client partition arguments need to be camelCase.
https://github.com/Unstructured-IO/unstructured-js-client/

It would be helpful if the README could contain an example with params which show the camelCase usage.

Thanks!

**Comment by awalker4** [comment]
Sorry for the very late response here. Just wanted to let you know that this is on our radar as we're revamping our api docs right now. I'll let you know when this is ready!

**Comment by awalker4** [comment]
This is now clarified here: https://docs.unstructured.io/api-reference/api-services/api-parameters
