### ISSUE TITLE
Error not returned

### ISSUE THREAD

**Issue by nicolofranceschi** [Unstructured-IO/unstructured-js-client#35]
If my server have some error the request just idle with return any error

**Comment by awalker4** [comment]
Hi there, sorry for the late response. We're revamping some of the retry handling in the client, which can certainly be opaque and just appear like a hang. For now, I'm recommend disable retries like so:
```
 const client = new UnstructuredClient({
    security: { apiKeyAuth: UNSTRUCTRED_API_KEY },
    serverURL: UNSTRUCTURED_SERVER_URL,
    retryConfig: {
      strategy: 'none',
      retryConnectionErrors: true,
      backoff: {}
    },
  })

```

**Comment by awalker4** [comment]
Please let me know if this resolves the long idle times - I'll close this for now.

**Comment by nicolofranceschi** [comment]
backoff: {} is required ?  there are some TS error for that

**Comment by awalker4** [comment]
Ah, apologies - you should be able to remove the backoff param.
