### ISSUE TITLE
Expose `unique_element_ids` to JS client

### ISSUE THREAD

**Issue by omikader** [Unstructured-IO/unstructured-js-client#49]
Can we expose a new partition parameter called `uniqueElementIds` now that https://github.com/Unstructured-IO/unstructured-api/pull/399 is merged/released?

**Comment by awalker4** [comment]
Absolutely! The clients here are autogenerated so they'll get updated as soon as the param is in our openapi spec. (Just got merged [here](https://github.com/Unstructured-IO/unstructured-js-client/pull/50)). Note that we do have some breaking changes coming that I want to coordinate with the python client, so I've disabled npm publishing just for a little bit here. I'll bump priority on getting the changes through so we can expose that param.

**Comment by awalker4** [comment]
The new 0.11.0 is published and includes `uniqueElementIds`! You can see all the current client params here: https://docs.unstructured.io/api-reference/api-services/api-parameters
